//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CoreProject.Models.Published
{
	/// <summary>Test Page</summary>
	[PublishedContentModel("testPage")]
	public partial class TestPage : PublishedContentModel, IContentBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "testPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TestPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TestPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Configurable Property Slider
		///</summary>
		[ImplementPropertyType("configurablePropertySlider")]
		public CoreProject.Models.MyAwesomePropertyEditor ConfigurablePropertySlider
		{
			get { return this.GetPropertyValue<CoreProject.Models.MyAwesomePropertyEditor>("configurablePropertySlider"); }
		}

		///<summary>
		/// Property Slider
		///</summary>
		[ImplementPropertyType("propertySlider")]
		public CoreProject.Models.MyAwesomePropertyEditor PropertySlider
		{
			get { return this.GetPropertyValue<CoreProject.Models.MyAwesomePropertyEditor>("propertySlider"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("bodyText")]
		public Newtonsoft.Json.Linq.JToken BodyText
		{
			get { return CoreProject.Models.Published.ContentBase.GetBodyText(this); }
		}

		///<summary>
		/// Page Title: The title of the page, this is also the first text in a google search result. The ideal length is between 40 and 60 characters
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return CoreProject.Models.Published.ContentBase.GetPageTitle(this); }
		}
	}
}
